// DB_지역풍속 — KBC2016 기준 172개 지역
// 구조검토_최종확정_v76.5_양주확정.xlsx에서 1:1 이식
// ★★★ 임의 수정 금지. 엑셀 원본 데이터.

export interface WindData {
  sido: string;
  sigungu: string;
  Vo: number;
  Kzr_B: number;
  Gf_B: number;
}

export const WIND_DB: WindData[] = [
  { sido: '서울특별시', sigungu: '서울(전역)', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '인천광역시', sigungu: '인천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '인천광역시', sigungu: '영종도/서', Vo: 34, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '인천광역시', sigungu: '영종도/동', Vo: 32, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '인천광역시', sigungu: '강화/서', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '인천광역시', sigungu: '강화/동', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '김포', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '구리', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '고양', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '파주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '양주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '의정부', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '동두천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '포천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '남양주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '가평', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '연천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '수원', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '군포', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '오산', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '화성', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '화성/서', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '의왕', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '부천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '안양', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '과천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '광명', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '안산', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '시흥', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '평택', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '하남', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '성남', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '광주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '양평', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '용인', Vo: 36, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '안성', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '여주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경기도', sigungu: '이천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '속초', Vo: 38, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '고성', Vo: 38, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '양양', Vo: 36, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '강릉', Vo: 36, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '동해', Vo: 32, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '삼척', Vo: 31, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '홍천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '정선', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '인제', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '양구', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '철원', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '화천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '춘천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '횡성', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '원주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '평창', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '영월', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '강원도', sigungu: '태백', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '태안/서', Vo: 40, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '태안/동', Vo: 38, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '서산', Vo: 36, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '서천', Vo: 37, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '당진', Vo: 32, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청북도', sigungu: '청주', Vo: 32, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청북도', sigungu: '청원', Vo: 32, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '세종특별자치시', sigungu: '세종', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '대전광역시', sigungu: '대전', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '보령', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '홍성', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '예산', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '공주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '부여', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '아산', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '계룡', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '천안', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '청양', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '논산', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청남도', sigungu: '금산', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청북도', sigungu: '진천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청북도', sigungu: '증평', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청북도', sigungu: '음성', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청북도', sigungu: '충주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청북도', sigungu: '제천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청북도', sigungu: '단양', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청북도', sigungu: '괴산', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청북도', sigungu: '보은', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청북도', sigungu: '영동', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '충청북도', sigungu: '옥천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '울릉도', Vo: 46, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '부산광역시', sigungu: '부산', Vo: 40, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '부산광역시', sigungu: '부산/서남', Vo: 42, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '부산광역시', sigungu: '기장', Vo: 41, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '포항', Vo: 41, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '통영', Vo: 38, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '거제', Vo: 38, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '경주', Vo: 36, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '영양', Vo: 36, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '고성(경남)', Vo: 36, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '울산광역시', sigungu: '울산', Vo: 36, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '울산광역시', sigungu: '울주', Vo: 36, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '양산', Vo: 36, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '김해', Vo: 35, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '창원', Vo: 34, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '울진', Vo: 34, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '남해', Vo: 32, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '대구광역시', sigungu: '대구', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '대구광역시', sigungu: '달성', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '경산', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '군위', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '함안', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '사천', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '영천', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '청송', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '청도', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '밀양', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '하동', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '칠곡', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '성주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '고령', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '창녕', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '진주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '영덕', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '봉화', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '영주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '예천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '문경', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '상주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '안동', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '의성', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '구미', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상북도', sigungu: '김천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '의령', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '거창', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '산청', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '합천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '경상남도', sigungu: '함양', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '완도', Vo: 40, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '군산', Vo: 38, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '여수', Vo: 38, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '진도', Vo: 36, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '신안', Vo: 36, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '목포', Vo: 35, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '무안', Vo: 34, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '해남', Vo: 32, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '고흥', Vo: 32, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '영광', Vo: 32, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '함평', Vo: 32, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '강진', Vo: 31, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '익산', Vo: 31, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '장흥', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '광양', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '부안', Vo: 30, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '영암', Vo: 29, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '나주', Vo: 29, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '고창', Vo: 29, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '광주광역시', sigungu: '광주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '순천', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '보성', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '장성', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '담양', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '곡성', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라남도', sigungu: '구례', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '전주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '완주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '김제', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '정읍', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '남원', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '순창', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '임실', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '무주', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '진안', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '전라북도', sigungu: '장수', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '제주특별자치도', sigungu: '제주', Vo: 48, Kzr_B: 0.81, Gf_B: 2.2 },
  { sido: '제주특별자치도', sigungu: '서귀포', Vo: 46, Kzr_B: 0.81, Gf_B: 2.2 },
];

export function lookupWindSpeed(sido: string, sigungu: string): WindData {
  const exact = WIND_DB.find(w => w.sido === sido && w.sigungu === sigungu);
  if (exact) return exact;
  const partial = WIND_DB.find(w =>
    w.sido === sido && (w.sigungu.includes(sigungu) || sigungu.includes(w.sigungu))
  );
  if (partial) return partial;
  const fallback = WIND_DB.find(w => w.sido === sido);
  if (fallback) return fallback;
  return { sido: '서울특별시', sigungu: '서울(전역)', Vo: 28, Kzr_B: 0.81, Gf_B: 2.2 };
}